### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by jthorst** [Thinkwise/docs#127]

**Comment by jthorst** [comment]
![image](https://user-images.githubusercontent.com/38907970/69800265-300bb000-11d5-11ea-9a36-d12bbddedabd.png)
Why is this here? I don't think this should be public.

**Comment by jsprklst** [comment]
Due to the way we're using Docusaurus, the Next version is exactly the same as the latest version in production. We need this version to be able to verify our changes during development.
