### ISSUE TITLE
Report Action Values missing

### ISSUE THREAD

**Issue by harmhorstman** [Thinkwise/docs#50]
A list of valid values for report Properties is missing. (e.g. 1 = Preview, 2 = Export to PDF, etc.)

![2019-05-22_10-18-53](https://user-images.githubusercontent.com/50906026/58159219-511aa380-7c7c-11e9-950a-92e1f69f8044.png)

<https://office.thinkwisesoftware.com/docs/docs/sf/reports.html>

**Comment by jsprklst** [comment]
Thanks for reporting this, we'll add the available options!
